### ISSUE TITLE
Finalize step missing from run-steps diagram

### ISSUE THREAD

**Issue by chrislemaire** [ldbc/ldbc_graphalytics_docs#6]
The specs now list the following benchmark run steps:
`“prepare", “startup", “run", “validate", “finalize", “terminate", and “archive".`
(https://github.com/ldbc/ldbc_graphalytics_docs/blob/master/tex/process.tex#L265)

[The diagram for run-steps](https://github.com/ldbc/ldbc_graphalytics_docs/blob/master/figures/benchmark_process.pdf), however, is still outdated, missing the `finalize` step:

**Comment by szarnyasg** [comment]
It is there as step 5, but it is named "report" instead of "finalize". Additionally, step 2 "startup" should be "setup".

I tried to fix it on https://jgraph.github.io/, but got various errors - "405 Not Allowed", "I/O error (send request)" - during save and export.

Update: I managed to reexport it using https://www.draw.io/. Sending the PR...
